"""empty message

Revision ID: 157fe938ace4
Revises: ba07a0c294d6
Create Date: 2020-07-09 18:01:29.325640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157fe938ace4'
down_revision = 'ba07a0c294d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
