"""empty message

Revision ID: f61d3d451202
Revises: 6d721fd3b3c6
Create Date: 2020-07-02 19:07:14.713645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61d3d451202'
down_revision = '6d721fd3b3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_list', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('show_list', sa.Column('venue_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'show_list', 'venue', ['venue_name'], ['name'])
    op.create_foreign_key(None, 'show_list', 'artist', ['artist_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show_list', type_='foreignkey')
    op.drop_constraint(None, 'show_list', type_='foreignkey')
    op.drop_column('show_list', 'venue_name')
    op.drop_column('show_list', 'artist_name')
    # ### end Alembic commands ###
